/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.roger.dat159.blockchain.application;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
	@Test
	public void testAppHasAGreeting() {
		DemoApplication classUnderTest = new DemoApplication();
		assertNotNull("app should have a greeting", classUnderTest.toString());
	}
}
